/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package discoveringlatentsemantic;

import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import textsimilarity.TextSimilarity;

/**
 *
 * @author Elcot
 */
public class FuzzyClustering extends javax.swing.JFrame {

    /**
     * Creates new form FuzzyClustering
     */
    public static int k=0;
    public static long fuzzyexetime=0;
    
    public FuzzyClustering() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Andalus", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fuzzy Clustering");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
        );

        jButton1.setText("Fuzzy Clustering");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
            //Fuzzy Clustering
        ArrayList cls = new ArrayList();
        long starttime=System.currentTimeMillis();
        long usedMemoryStart = Runtime.getRuntime().freeMemory();
        k=Integer.parseInt(JOptionPane.showInputDialog(this,"Enter the No of Clusters to be Generated: "));
        
        ArrayList NERecog=NERFrame.NERecog;
        ArrayList allfeatures=FutureExtraction.allfeatures;
        ArrayList countonly=new ArrayList();
        ArrayList idwithcount=new ArrayList();
        System.out.println("NERecog size : " + NERecog.size());
        for(int i=0;i<NERecog.size()-1;i++)
        {
            System.out.println(NERecog.get(i).toString().trim());
            String s[]=NERecog.get(i).toString().trim().split("-->");
            String rep=s[1].trim().replaceAll("\n"," ");
            
            String sp[]=rep.trim().split(" ");
            int count=0;
            for(int j=0;j<sp.length;j++)
            {
                if(allfeatures.contains(sp[j].trim().toLowerCase()))
                {
                    count++;
                }
            }
            countonly.add(count);
            idwithcount.add(s[0].trim()+"-->"+count);
        }
        Collections.sort(countonly,Collections.reverseOrder());
        ArrayList clus[]=new ArrayList[k];
        for(int i=0;i<clus.length;i++)
        {
            clus[i]=new ArrayList();
        }
        int cou=0,j=0;
        int re=NERecog.size()/k;
        
        ArrayList norep=new ArrayList();
        for(int i=0;i<countonly.size();i++)
        {
            String freq=countonly.get(i).toString().trim();
            for(int l=0;l<idwithcount.size();l++)
            {
                String topickeyvalue[]=idwithcount.get(l).toString().trim().split("-->");
                if(freq.trim().equals(topickeyvalue[1].trim()))
                {
                    if(!(norep.contains(topickeyvalue[0].trim())))
                    {
                        norep.add(topickeyvalue[0].trim());
                        clus[j].add(topickeyvalue[0].trim());
                        cls.add(topickeyvalue[0].trim());
                        cou++;
                        if(!(j==(k-1)))
                        {
                            if(cou==re)
                            {
                                j++;
                                cou=0;
                            }
                        }
                    }
                }
            }
        }
        System.out.println("NERecog.size(): "+NERecog.size());
        String ro="";
//        for(int i=0;i<clus.length;i++)
//        {
//            System.out.println("=================================================================================");
//            System.out.println("Cluster - "+(i+1));
//            System.out.println("=================================================================================");
//            String co="";
//            for(int l=0;l<clus[i].size();l++)   
//            {
//                String val=clus[i].get(l).toString().trim();
//                System.out.println(val.trim());
//                co=co+val.trim()+"\n";
//            }
//            String col=co.substring(0,co.lastIndexOf('\n'));
//            ro=ro+"=================================================\nCluster - "+(i+1)+"\n=================================================\n"+col.trim()+"\n";
//        }
//        String row=ro.substring(0,ro.lastIndexOf('\n'));
//        jTextArea1.setText(row.trim());
        
        //***********************************CONTENT BASED CLUSTERING***********************************
        String result = null;
        try{
            result = assignCluster(cls);
            jTextArea1.setText(result);
        }catch(Exception ex){
            System.out.println(ex.getCause());
        }
         //***********************************************END*******************************************
        long stoptime=System.currentTimeMillis();
        long usedMemoryEnd = Runtime.getRuntime().freeMemory();
        Details.fuzzySpace = usedMemoryEnd - usedMemoryStart;
        fuzzyexetime=stoptime-starttime;
    }//GEN-LAST:event_jButton1ActionPerformed

    public String readFile(String fileName)throws Exception{
        File file = new File("Web Documents\\"+fileName);
        FileInputStream fis = new FileInputStream(file);
        byte data[] = new byte[fis.available()];
        fis.read(data);
        fis.close();
        String str = new String(data);
        return str;
    }
    public ArrayList readFileName(){ 
        ArrayList fileNames = new ArrayList();
        String path = "Web Documents/";  
        String files;
        File folder = new File(path);
        File[] listOfFiles = folder.listFiles();
        for (int i = 0; i < listOfFiles.length; i++) {
            String name = listOfFiles[i].getName();
            fileNames.add(name);    
        }
        Collections.reverse(fileNames);
        System.out.println("fileNames : " + fileNames);
        return fileNames;
    }
    public String assignCluster() throws Exception{
        TextSimilarity ts = new TextSimilarity();
        ArrayList fileNames = readFileName();
        Collections.reverse(fileNames);
        int k;
        do{
            k = Integer.parseInt(JOptionPane.showInputDialog("Enter no of cluster : "));
        }while(k <= 1 || k >= 10);
        ArrayList cluster[] = new ArrayList[k];
        int i = 0;
        for (; i < cluster.length; i++) {
            cluster[i] = new ArrayList();
            cluster[i].add(fileNames.get(i));
        }
        ArrayList percent = new ArrayList();
        
        for (int fileCtr = k; fileCtr < fileNames.size(); fileCtr++) {
            String compareFileName = fileNames.get(fileCtr).toString();
            for (int c = 0; c < cluster.length; c++) {
                String clusterFileName = cluster[c].get(0).toString();
                double similarity = 0;
                String str1 = readFile(clusterFileName);
                String str2 = readFile(compareFileName);
                similarity = ts.similarity(str1, str2);
                percent.add(similarity);
            }
            double max = Double.parseDouble(Collections.max(percent).toString());
            int index = percent.indexOf(max);
            cluster[index].add(compareFileName);
            percent = new ArrayList();
        }
        String result = "";
        for (int j = 0; j < cluster.length; j++) {
            ArrayList c = cluster[j];
            int n = j+1;
            result += "*********************Cluster " + n + "**************************\n";
            for (int l = 0; l < c.size(); l++) {
                String fname = c.get(l).toString();
                result += fname + "\n";
            }
            result += "*************************************************************\n\n";
        }
        String res = "";
         for (int j = 0; j < cluster.length; j++) {
            ArrayList c = cluster[j];
            for (int l = 0; l < c.size(); l++) {
                String fname = c.get(l).toString();
                res += fname + "\n";
            }
             System.out.println(res);
        }
        System.out.println("Result : ");
        System.out.println(result);
        return result;
    }
    
    public String assignCluster(ArrayList clus) throws Exception{
        TextSimilarity ts = new TextSimilarity();
        ArrayList fileNames = clus;
        Collections.reverse(fileNames);
        int k = FuzzyClustering.k;

        ArrayList cluster[] = new ArrayList[k];
        int i = 0;
        for (; i < cluster.length; i++) {
            cluster[i] = new ArrayList();
            cluster[i].add(fileNames.get(i));
        }
        ArrayList percent = new ArrayList();
        
        for (int fileCtr = k; fileCtr < fileNames.size(); fileCtr++) {
            String compareFileName = fileNames.get(fileCtr).toString();
            for (int c = 0; c < cluster.length; c++) {
                String clusterFileName = cluster[c].get(0).toString();
                double similarity = 0;
                String str1 = readFile(clusterFileName);
                String str2 = readFile(compareFileName);
                similarity = ts.similarity(str1, str2);
                percent.add(similarity);
            }
            double max = Double.parseDouble(Collections.max(percent).toString());
            int index = percent.indexOf(max);
            cluster[index].add(compareFileName);
            percent = new ArrayList();
        }
        String result = "";
        for (int j = 0; j < cluster.length; j++) {
            ArrayList c = cluster[j];
            int n = j+1;
            result += "*********************Cluster " + n + "**************************\n";
            for (int l = 0; l < c.size(); l++) {
                String fname = c.get(l).toString();
                result += fname + "\n";
            }
            result += "*************************************************************\n\n";
        }
        String res = "";
         for (int j = 0; j < cluster.length; j++) {
            ArrayList c = cluster[j];
            for (int l = 0; l < c.size(); l++) {
                String fname = c.get(l).toString();
                res += fname + "\n";
            }
             System.out.println(res);
        }
        System.out.println("Result : ");
        System.out.println(result);
        return result;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuzzyClustering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuzzyClustering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuzzyClustering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuzzyClustering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuzzyClustering().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
